#!/usr/bin/env python3
"""
Test harness for the space prototype's pure-logic modules.

The standalone Luau CLI sandboxes its global table, so Roblox globals cannot
be injected into a required module. Instead this script assembles the REAL
module sources into a single Luau chunk, preceded by the stub definitions as
plain locals -- which the module bodies then close over as upvalues.

The modules are used verbatim: no source is rewritten except the
`require(script.Parent:WaitForChild("X"))` lines, which are rebound to the
already-assembled local of the same name.

Usage:  python3 tests/harness.py [path/to/luau]
"""
import re
import subprocess
import sys
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULES = ROOT / "src" / "ReplicatedStorage" / "Modules"
TESTS = ROOT / "tests"

# Dependency order: each module may only reference ones already assembled.
ORDER = ["FlightConfig", "Protocol", "PlanetController", "LandingController", "FlightController"]

REQUIRE_RE = re.compile(
    r'require\(\s*script\.Parent[^)]*?:WaitForChild\(\s*"(?P<name>\w+)"\s*\)\s*\)'
)


def wrap(name: str) -> str:
    source = (MODULES / f"{name}.luau").read_text()
    # Rebind intra-module requires to the locals assembled above.
    source, count = REQUIRE_RE.subn(lambda m: m.group("name"), source)
    body = "\n".join("\t" + line if line.strip() else line for line in source.splitlines())
    return f"-- ==== {name}.luau ({count} require(s) rebound) ====\n" \
           f"local {name} = (function()\n{body}\nend)()\n"


def build() -> str:
    parts = [
        "-- GENERATED by tests/harness.py -- do not edit.\n",
        (TESTS / "Prelude.luau").read_text(),
        "\n",
    ]
    parts += [wrap(name) for name in ORDER]
    parts.append("\n-- ==== Spec.luau ====\n")
    parts.append((TESTS / "Spec.luau").read_text())
    return "".join(parts)


def main() -> int:
    luau = sys.argv[1] if len(sys.argv) > 1 else shutil.which("luau")
    if not luau:
        print("error: luau CLI not found. Pass its path, or install from")
        print("       https://github.com/luau-lang/luau/releases")
        return 2

    generated = TESTS / "_generated.luau"
    generated.write_text(build())

    result = subprocess.run([luau, str(generated)], cwd=TESTS)
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
